Repository lanl/scico, pull requests merged in 2021-11, with the labels that each got.

#72 Improve LinearOperator adjoint tests
  scico/linop/__init__.py
  scico/linop/_linop.py
  scico/test/linop/test_circconv.py
  scico/test/linop/test_convolve.py
  scico/test/linop/test_dft.py
  scico/test/linop/test_diff.py
  scico/test/linop/test_linop.py
  scico/test/linop/test_optics.py
  scico/test/linop/test_radon_astra.py
  scico/test/linop/test_radon_svmbir.py
  scico/test/linop/test_stack.py
  scico/util.py
Labels: enhancement, tests

#76 Improve usage overview docs
  docs/source/_static/scico.css
  docs/source/classes.rst
  docs/source/index.rst
  docs/source/optimizer.rst
  docs/source/overview.rst
  docs/source/references.bib
Labels: documentation

#79 Add function to compute operator norm
  scico/linop/__init__.py
  scico/linop/_linop.py
  scico/test/linop/test_linop.py
Labels: enhancement

#87 Consistent notation for Hermitian conjugate
  docs/source/notes.rst
  scico/admm.py
  scico/loss.py
Labels: documentation

#85 Add tests for DnCNN
  .github/workflows/pytest.yml
  scico/functional/_denoiser.py
  scico/functional/_flax.py
  scico/test/test_functional.py
Labels: tests

#78 Problem with W^1/2 weight exponent
  docs/source/functional.rst
  examples/scripts/ct_astra_weighted_tv_admm.py
  examples/scripts/ct_svmbir_ppp_bm3d_admm_cg.py
  examples/scripts/ct_svmbir_ppp_bm3d_admm_prox.py
  scico/admm.py
  scico/linop/radon_svmbir.py
  scico/loss.py
  scico/test/linop/test_radon_svmbir.py
  scico/test/test_functional.py
Labels: bug, priority: high

#99 Skip test based on content of scico/data/examples
  scico/test/test_data.py
Labels: tests

#88 Changes to admm and svmbir wrapper to address issue #57
  .gitignore
  docs/source/team.rst
  examples/scripts/ct_svmbir_ppp_bm3d_admm_cg.py
  examples/scripts/ct_svmbir_ppp_bm3d_admm_prox.py
  examples/scripts/denoise_tv_iso_pgm.py
  misc/conda/make_conda_env.sh
  requirements.txt
  scico/admm.py
  scico/functional/_denoiser.py
  scico/functional/_flax.py
  scico/functional/_functional.py
  scico/functional/_indicator.py
  scico/functional/_norm.py
  scico/linop/radon_astra.py
  scico/linop/radon_svmbir.py
  scico/loss.py
  scico/test/linop/test_radon_svmbir.py
  scico/test/test_admm.py
  scico/test/test_functional.py
Labels: bug, priority: high

#106 Add pylint check for missing docstrings
  .github/workflows/lint_optional.yml
  scico/__init__.py
  scico/_autograd.py
  scico/_generic_operators.py
  scico/blockarray.py
  scico/linop/optics.py
  scico/linop/radon_astra.py
  scico/numpy/__init__.py
  scico/numpy/linalg.py
Labels: documentation

#114 Stop codecov checking the patch
  .github/codecov.yml
Labels: tests, developer

#107 Fix ASTRA test in GPU issue #103
  scico/linop/_linop.py
  scico/test/linop/test_linop.py
  scico/test/linop/test_radon_astra.py
Labels: tests

#108 Clean up notebooks build script
  examples/Makefile
  examples/README.rst
  examples/makejnb.py
  examples/makenotebooks.py
  examples/pytojnb.sh
Labels: examples

#115 Add missing requirement
  examples/examples_requirements.txt
  examples/scripts/deconv_microscopy_allchn_tv_admm.py
Labels: examples
