Repository lanl/scico, pull requests merged in 2021-12, with the labels that each got.

#118 Add optional relaxation to ADMM solver
  scico/admm.py
  scico/test/test_admm.py
Labels: enhancement

#120 Add codefactor badge
  README.rst
Labels: developer

#119 Docstring cleanup and improvement of style guide compliance
  docs/source/conf.py
  scico/__init__.py
  scico/_autograd.py
  scico/_generic_operators.py
  scico/admm.py
  scico/blockarray.py
  scico/data/__init__.py
  scico/diagnostics.py
  scico/flax.py
  scico/functional/__init__.py
  scico/functional/_denoiser.py
  scico/functional/_flax.py
  scico/functional/_functional.py
  scico/functional/_indicator.py
  scico/functional/_norm.py
  scico/linop/_circconv.py
  scico/linop/_convolve.py
  scico/linop/_dft.py
  scico/linop/_diff.py
  scico/linop/_matrix.py
  scico/linop/_stack.py
  scico/linop/optics.py
  scico/linop/radon_astra.py
  scico/linop/radon_svmbir.py
  scico/loss.py
  scico/math.py
  scico/metric.py
  scico/numpy/__init__.py
  scico/numpy/_create.py
  scico/numpy/_util.py
  scico/numpy/fft.py
  scico/numpy/linalg.py
  scico/operator/biconvolve.py
  scico/pgm.py
  scico/plot.py
  scico/random.py
  scico/scipy/special.py
  scico/solver.py
  scico/typing.py
  scico/util.py
Labels: documentation, developer

#121 Added Markup section.
  docs/source/style.rst
Labels: documentation, developer

#125 Clean up scico.solver module
  scico/solver.py
  scico/test/test_solver.py
Labels: documentation

#126 Run pytest on latest jax version
  .github/workflows/pytest.yml
Labels: developer

#128 Add ray.tune interface and example script
  .github/workflows/pytest.yml
  docs/source/conf.py
  examples/examples_requirements.txt
  examples/scripts/deconv_microscopy_allchn_tv_admm.py
  examples/scripts/deconv_tv_admm_tune.py
  scico/ray/__init__.py
  scico/ray/tune.py
  scico/test/test_ray_tune.py
Labels: enhancement, examples

#130 Improve iteration statistics mechanism
  examples/scripts/ct_astra_tv_admm.py
  examples/scripts/ct_astra_weighted_tv_admm.py
  examples/scripts/ct_svmbir_ppp_bm3d_admm_cg.py
  examples/scripts/ct_svmbir_ppp_bm3d_admm_prox.py
  examples/scripts/ct_svmbir_tv_multi.py
  examples/scripts/deconv_circ_tv_admm.py
  examples/scripts/deconv_microscopy_allchn_tv_admm.py
  examples/scripts/deconv_microscopy_tv_admm.py
  examples/scripts/deconv_ppp_bm3d_admm.py
  examples/scripts/deconv_ppp_bm3d_pgm.py
  examples/scripts/deconv_ppp_dncnn_admm.py
  examples/scripts/deconv_tv_admm.py
  examples/scripts/deconv_tv_admm_tune.py
  examples/scripts/demosaic_ppp_bm3d_admm.py
  examples/scripts/denoise_tv_iso_admm.py
  examples/scripts/denoise_tv_iso_multi.py
  examples/scripts/denoise_tv_iso_pgm.py
  examples/scripts/sparsecode_admm.py
  examples/scripts/sparsecode_pgm.py
  examples/scripts/sparsecode_poisson_blkarr_pgm.py
  examples/scripts/sparsecode_poisson_pgm.py
  scico/admm.py
  scico/diagnostics.py
  scico/ladmm.py
  scico/pgm.py
  scico/primaldual.py
  scico/test/test_admm.py
  scico/test/test_diagnostics.py
  scico/test/test_ladmm.py
  scico/test/test_pdhg.py
  scico/test/test_pgm.py
Labels: enhancement

#131 Fix bugs in linop.optics
  scico/linop/optics.py
  scico/test/linop/test_optics.py
Labels: bug

#135 Address codefactor complaints
  .github/isbin.sh
  CHANGES.rst
  docs/source/_static/scico.css
  docs/source/conf.py
  docs/source/docutil.py
  examples/makenotebooks.py
  examples/scriptcheck.sh
  misc/conda/install_conda.sh
  misc/conda/make_conda_env.sh
  scico/_generic_operators.py
  scico/blockarray.py
  scico/diagnostics.py
  scico/functional/_flax.py
  scico/functional/_functional.py
  scico/functional/_norm.py
  scico/linop/_circconv.py
  scico/linop/_convolve.py
  scico/linop/_linop.py
  scico/linop/_matrix.py
  scico/linop/_stack.py
  scico/linop/radon_astra.py
  scico/linop/radon_svmbir.py
  scico/loss.py
  scico/math.py
  scico/numpy/_create.py
  scico/numpy/_util.py
  scico/numpy/linalg.py
  scico/operator/biconvolve.py
  scico/optimize/pgm.py
  scico/plot.py
  scico/solver.py
  scico/test/linop/test_linop.py
  scico/test/linop/test_matrix.py
  scico/test/optimize/test_admm.py
  scico/test/optimize/test_ladmm.py
  scico/test/optimize/test_pdhg.py
  scico/test/test_functional.py
  scico/test/test_numpy.py
  scico/test/test_random.py
  scico/test/test_solver.py
  scico/test/test_util.py
  scico/util.py
  setup.py
Labels: enhancement

#140 Modify cg_kwargs mechanism in admm.LinearSubproblemSolver
  examples/scripts/ct_astra_tv_admm.py
  examples/scripts/ct_astra_weighted_tv_admm.py
  examples/scripts/ct_svmbir_ppp_bm3d_admm_cg.py
  examples/scripts/ct_svmbir_ppp_bm3d_admm_prox.py
  examples/scripts/ct_svmbir_tv_multi.py
  examples/scripts/deconv_ppp_bm3d_admm.py
  examples/scripts/deconv_ppp_dncnn_admm.py
  examples/scripts/demosaic_ppp_bm3d_admm.py
  examples/scripts/denoise_tv_iso_admm.py
  scico/optimize/admm.py
  scico/test/optimize/test_admm.py
Labels: enhancement, examples

#141 Add pylint to `pre-commit`
  .pre-commit-config.yaml
  dev_requirements.txt
  docs/source/contributing.rst
Labels: developer
