Repository lanl/scico, pull requests merged in 2022-04, with the labels that each got.

#269 Minor docs fix
  scico/linop/optics.py
Labels: documentation

#273 Make compatible with jax v0.3.5
  requirements.txt
  scico/linop/_matrix.py
  scico/loss.py
  scico/solver.py
  scico/test/functional/test_loss.py
  scico/test/linop/test_linop.py
  scico/test/test_blockarray.py
  scico/test/test_operator.py
Labels: bug, developer

#271 Change development version number structure
  docs/source/conf.py
  scico/__init__.py
  scico/_version.py
  scico/optimize/admm.py
  scico/test/test_version.py
  setup.py
Labels: developer

#278 Improve `SquaredL2SquaredAbsLoss`
  scico/loss.py
  scico/test/functional/test_loss.py
Labels: enhancement

#259 Simplify `BlockArray` implementation
  docs/source/notes.rst
  docs/source/operator.rst
  examples/scripts/denoise_tv_iso_pgm.py
  examples/scripts/sparsecode_poisson_pgm.py
  scico/_flax.py
  scico/_generic_operators.py
  scico/blockarray.py
  scico/denoiser.py
  scico/functional/_dist.py
  scico/functional/_functional.py
  scico/functional/_indicator.py
  scico/functional/_norm.py
  scico/linop/_circconv.py
  scico/linop/_convolve.py
  scico/linop/_diff.py
  scico/linop/_linop.py
  scico/linop/_matrix.py
  scico/linop/_stack.py
  scico/linop/optics.py
  scico/loss.py
  scico/metric.py
  scico/numpy/__init__.py
  scico/numpy/_create.py
  scico/numpy/_util.py
  scico/numpy/_wrapped_function_lists.py
  scico/numpy/_wrappers.py
  scico/numpy/blockarray.py
  scico/numpy/fft.py
  scico/numpy/linalg.py
  scico/numpy/util.py
  scico/operator/biconvolve.py
  scico/optimize/_ladmm.py
  scico/optimize/_primaldual.py
  scico/optimize/admm.py
  scico/optimize/pgm.py
  scico/random.py
  scico/scipy/special.py
  scico/solver.py
  scico/test/functional/test_core.py
  scico/test/functional/test_loss.py
  scico/test/functional/test_separable.py
  scico/test/linop/test_abel.py
  scico/test/linop/test_diff.py
  scico/test/linop/test_linop.py
  scico/test/linop/test_radon_svmbir.py
  scico/test/optimize/test_ladmm.py
  scico/test/optimize/test_pdhg.py
  scico/test/test_array.py
  scico/test/test_biconvolve.py
  scico/test/test_blockarray.py
  scico/test/test_numpy.py
  scico/test/test_operator.py
  scico/test/test_random.py
  scico/test/test_ray_tune.py
  scico/test/test_solver.py
Labels: improvement
