Repository lanl/scico, pull requests merged in 2022-03, with the labels that each got.

#248 Fix readthedocs build failure
  .readthedocs.yaml
  docs/docs_requirements.txt
  scico/_autograd.py
  scico/ray/__init__.py
Labels: documentation

#247 Add doctest of modules to workflow, fix modules so they pass
  .github/workflows/pytest.yml
  conftest.py
  docs/source/conf.py
  pytest.ini
  scico/linop/_diff.py
  scico/util.py
  setup.py
Labels: documentation, tests

#251 Address missing examples in docs
  .readthedocs.yaml
Labels: documentation

#254 Minor clean up and packaging fix
  MANIFEST.in
  docs/source/conf.py
  scico/blockarray.py
  scico/diagnostics.py
  scico/functional/_functional.py
  scico/linop/_convolve.py
  scico/linop/_dft.py
  scico/linop/_linop.py
  scico/linop/_matrix.py
  scico/linop/optics.py
  scico/loss.py
  scico/metric.py
  scico/plot.py
  scico/typing.py
  scico/util.py
Labels: developer

#255 Fix bugs in `loss` module
  scico/diagnostics.py
  scico/loss.py
  scico/optimize/admm.py
Labels: bug, improvement

#258 Add support for addition of functionals
  CHANGES.rst
  scico/functional/_functional.py
  scico/solver.py
  scico/test/test_functional.py
Labels: improvement

#260 Sphinx autodoc configuration changes
  docs/source/conf.py
  scico/linop/_linop.py
  scico/linop/optics.py
Labels: documentation

#262 Update and fix conda environment construction script
  misc/conda/README.rst
  misc/conda/make_conda_env.sh
Labels: developer

#264 Solver and functional extensions
  CHANGES.rst
  docs/docs_requirements.txt
  docs/source/references.bib
  scico/functional/__init__.py
  scico/functional/_dist.py
  scico/functional/_indicator.py
  scico/functional/_norm.py
  scico/solver.py
  scico/test/functional/prox.py
  scico/test/functional/test_core.py
  scico/test/functional/test_denoiser_func.py
  scico/test/functional/test_loss.py
  scico/test/functional/test_misc.py
  scico/test/functional/test_separable.py
  scico/test/linop/test_radon_svmbir.py
  scico/test/test_solver.py
Labels: enhancement, tests

#268 Bump pinned `black` version
  .github/workflows/lint.yml
  dev_requirements.txt
  examples/scripts/deconv_ppp_bm3d_pgm.py
  examples/scripts/deconv_ppp_bm4d_admm.py
  examples/scripts/denoise_tv_iso_pgm.py
  scico/blockarray.py
  scico/examples.py
  scico/functional/_norm.py
  scico/linop/_linop.py
  scico/linop/optics.py
  scico/loss.py
  scico/metric.py
  scico/optimize/pgm.py
  scico/test/linop/test_abel.py
  scico/test/linop/test_optics.py
  scico/test/linop/test_radon_svmbir.py
  scico/test/optimize/test_admm.py
  scico/test/test_metric.py
  scico/test/test_operator.py
  scico/test/test_ray_tune.py
  scico/test/test_solver.py
Labels: developer

#233 Improve documentation for `linop.optics`
  docs/source/references.bib
  docs/source/team.rst
  scico/_generic_operators.py
  scico/array.py
  scico/linop/optics.py
  scico/test/linop/test_optics.py
  scico/util.py
Labels: documentation
