Repository lanl/scico, pull requests merged in 2022-02, with the labels that each got.

#201 Replace tabs with spaces
  .github/isbin.sh
  docs/Makefile
  docs/source/notes.rst
  docs/source/optimizer.rst
  docs/source/style.rst
  examples/scriptcheck.sh
  misc/conda/install_conda.sh
  misc/conda/make_conda_env.sh
Labels: documentation

#207 Remove double spacing instances
  README.rst
  docs/source/conf.py
  docs/source/contributing.rst
  docs/source/functional.rst
  docs/source/notes.rst
  docs/source/operator.rst
  docs/source/overview.rst
  docs/source/style.rst
  examples/scripts/demosaic_ppp_bm3d_admm.py
  scico/_generic_operators.py
  scico/blockarray.py
  scico/functional/_functional.py
  scico/linop/optics.py
  scico/linop/radon_astra.py
  scico/loss.py
  scico/optimize/admm.py
  scico/util.py
Labels: documentation

#210 Miscellaneous minor improvements
  .github/workflows/pytest.yml
  README.rst
  docs/source/overview.rst
  scico/_generic_operators.py
  scico/array.py
  scico/blockarray.py
  scico/functional/_functional.py
  scico/linop/_diff.py
  scico/linop/radon_svmbir.py
  scico/optimize/_ladmm.py
  scico/optimize/_primaldual.py
  scico/optimize/pgm.py
Labels: documentation, improvement

#214 Change svd call to avoid compute_uv=False
  scico/functional/_norm.py
Labels: bug, tests

#213 Move denoiser implementations out of `functional` sub-module
  scico/_flax.py
  scico/denoiser.py
  scico/functional/__init__.py
  scico/functional/_denoiser.py
  scico/functional/_flax.py
  scico/linop/_circconv.py
  scico/loss.py
  scico/solver.py
  scico/test/test_denoiser.py
  scico/test/test_flax.py
  scico/test/test_functional.py
Labels: improvement

#218 Address excessive memory usage in `functional.NuclearNorm.__call__`
  docs/source/references.bib
  scico/functional/_norm.py
Labels: improvement

#219 fix type annotations in pgm
  docs/source/style.rst
  scico/optimize/admm.py
  scico/optimize/pgm.py
Labels: improvement

#226 Preparation for next release
  .github/workflows/pytest_latest.yml
  CHANGES.rst
  README.rst
  scico/__init__.py
Labels: developer

#229 Check for blockarray inputs in from_operator
  scico/linop/_circconv.py
  scico/test/linop/test_circconv.py
Labels: improvement
