Repository lanl/scico, pull requests merged in 2022-01, with the labels that each got.

#156 Remove problematic array copy operations
  scico/optimize/_ladmm.py
  scico/optimize/_primaldual.py
  scico/test/optimize/test_ladmm.py
  scico/test/optimize/test_pdhg.py
Labels: bug

#169 Address readthedocs build failure
  docs/docs_requirements.txt
Labels: documentation

#150 Address TODO in code
  scico/blockarray.py
  scico/loss.py
  scico/numpy/__init__.py
  scico/scipy/special.py
  scico/typing.py
Labels: enhancement

#174 Silence docs build warnings
  docs/docs_requirements.txt
  docs/source/conf.py
  scico/flax.py
Labels: documentation

#162 Add array slicing `LinearOperator`
  scico/blockarray.py
  scico/linop/__init__.py
  scico/linop/_linop.py
  scico/test/linop/test_linop.py
  scico/test/test_blockarray.py
  scico/test/test_util.py
  scico/typing.py
  scico/util.py
Labels: enhancement

#175 Move some functions to different modules
  CHANGES.rst
  examples/scriptcheck.sh
  examples/scripts/denoise_tv_iso_pgm.py
  scico/_generic_operators.py
  scico/array.py
  scico/blockarray.py
  scico/functional/_norm.py
  scico/linop/_convolve.py
  scico/linop/_diff.py
  scico/linop/_linop.py
  scico/linop/optics.py
  scico/loss.py
  scico/math.py
  scico/metric.py
  scico/numpy/__init__.py
  scico/numpy/_create.py
  scico/operator/biconvolve.py
  scico/optimize/_ladmm.py
  scico/optimize/_primaldual.py
  scico/optimize/admm.py
  scico/optimize/pgm.py
  scico/random.py
  scico/test/linop/test_linop.py
  scico/test/test_array.py
  scico/test/test_math.py
  scico/test/test_metric.py
  scico/test/test_util.py
  scico/util.py
Labels: enhancement

#180 Make prox notation consistent
  docs/source/functional.rst
  examples/scripts/denoise_tv_iso_pgm.py
  scico/functional/_functional.py
  scico/functional/_indicator.py
  scico/functional/_norm.py
  scico/loss.py
Labels: documentation

#177 add center_offset to svmbir interface
  scico/linop/radon_svmbir.py
  scico/test/linop/test_radon_astra.py
  scico/test/linop/test_radon_svmbir.py
Labels: enhancement

#185 Fix some problems in DnCNN implementation and example
  LICENSE
  docs/source/conf.py
  examples/scripts/deconv_ppp_dncnn_admm.py
  scico/functional/_denoiser.py
Labels: bug

#186 Correct __module__ for wrapped functions
  scico/numpy/_util.py
Labels: bug

#187 Make output types jax-array
  scico/linop/radon_svmbir.py
Labels: oversight

#189 Make pytest-latest-jax workflow get latest jax even with SCICO jax version pinned
  .github/workflows/pytest.yml
Labels: bug, developer

#178 Update conda install scripts
  examples/notebooks_requirements.txt
  misc/conda/install_conda.sh
  misc/conda/make_conda_env.sh
  requirements.txt
Labels: packaging

#191 Refactor svmbir loss
  scico/linop/radon_astra.py
  scico/linop/radon_svmbir.py
  scico/loss.py
  scico/test/linop/test_radon_svmbir.py
Labels: improvement

#184 remove is_smooth attribute (#89)
  docs/source/functional.rst
  examples/scripts/denoise_tv_iso_pgm.py
  examples/scripts/sparsecode_poisson_blkarr_pgm.py
  examples/scripts/sparsecode_poisson_pgm.py
  scico/_generic_operators.py
  scico/functional/_denoiser.py
  scico/functional/_flax.py
  scico/functional/_functional.py
  scico/functional/_indicator.py
  scico/functional/_norm.py
  scico/loss.py
  scico/optimize/pgm.py
  scico/test/test_functional.py
  scico/test/test_operator.py
Labels: improvement

#194 Fix scico.random failure with latest jax version
  scico/random.py
Labels: bug

#192 Add Robust PCA example
  docs/source/examples.rst
  docs/source/references.bib
  examples/scripts/README.rst
  examples/scripts/index.rst
  examples/scripts/video_rpca_admm.py
  scico/_generic_operators.py
  scico/array.py
  scico/examples.py
  scico/functional/__init__.py
  scico/functional/_norm.py
  scico/optimize/__init__.py
  scico/optimize/_ladmm.py
  scico/optimize/_primaldual.py
  scico/optimize/admm.py
  scico/optimize/pgm.py
  scico/test/test_array.py
  scico/test/test_examples.py
  scico/test/test_functional.py
Labels: bug, enhancement, examples
