Repository lanl/scico, pull requests merged in 2022-05, with the labels that each got.

#176 Fix typing errors and set up `mypy` workflow action
  .github/workflows/mypy.yml
  scico/_flax.py
  scico/_generic_operators.py
  scico/_version.py
  scico/diagnostics.py
  scico/examples.py
  scico/functional/_denoiser.py
  scico/functional/_functional.py
  scico/linop/_circconv.py
  scico/linop/_diff.py
  scico/linop/_linop.py
  scico/linop/_stack.py
  scico/linop/abel.py
  scico/linop/optics.py
  scico/linop/radon_astra.py
  scico/linop/radon_svmbir.py
  scico/loss.py
  scico/numpy/__init__.py
  scico/numpy/blockarray.py
  scico/numpy/util.py
  scico/operator/biconvolve.py
  scico/optimize/_ladmm.py
  scico/optimize/_primaldual.py
  scico/optimize/admm.py
  scico/optimize/pgm.py
  scico/random.py
  scico/solver.py
  scico/typing.py
  scico/util.py
Labels: developer

#286 Fix parameter name in example script
  examples/scripts/video_rpca_admm.py
Labels: bug, examples

#285 Restore missing `BlockArray` docs
  docs/source/blockarray.rst
  docs/source/classes.rst
  docs/source/conf.py
  docs/source/operator.rst
  examples/scripts/sparsecode_poisson_pgm.py
  scico/numpy/__init__.py
  scico/numpy/_blockarray.py
  scico/numpy/_wrappers.py
  scico/numpy/blockarray.py
  scico/numpy/util.py
  scico/scipy/__init__.py
  scico/scipy/special.py
Labels: documentation

#282 Fix bugs introduced by BlockArray changes
  examples/scriptcheck.sh
  examples/scripts/denoise_tv_iso_pgm.py
  scico/denoiser.py
  scico/functional/_indicator.py
  scico/functional/_norm.py
  scico/linop/_linop.py
  scico/loss.py
  scico/numpy/_wrapped_function_lists.py
  scico/optimize/pgm.py
  scico/solver.py
  scico/test/functional/test_core.py
  scico/test/test_solver.py
Labels: bug

#290 Various improvements
  scico/linop/_circconv.py
  scico/linop/_convolve.py
  scico/linop/_diff.py
  scico/linop/_matrix.py
  scico/optimize/_admm.py
  scico/optimize/_admmaux.py
  scico/optimize/_ladmm.py
  scico/optimize/_pgm.py
  scico/optimize/_pgmaux.py
  scico/optimize/_primaldual.py
  scico/optimize/admm.py
  scico/optimize/pgm.py
Labels: documentation, standards, typing

#289 Improve docs
  scico/numpy/util.py
Labels: documentation

#294 Bump maximum `jax` version and address `imageio` warnings
  .github/workflows/pytest_latest.yml
  requirements.txt
  scico/data/__init__.py
  scico/examples.py
  scico/test/test_examples.py
Labels: improvement

#295 Improve example checking script
  .github/workflows/test_examples.yml
  docs/source/contributing.rst
  examples/README.rst
  examples/scriptcheck.sh
  examples/scripts/ct_abel_tv_admm.py
  examples/scripts/ct_abel_tv_admm_tune.py
  examples/scripts/deconv_circ_tv_admm.py
  examples/scripts/deconv_microscopy_tv_admm.py
  examples/scripts/deconv_ppp_bm3d_admm.py
  examples/scripts/deconv_ppp_bm3d_pgm.py
  examples/scripts/deconv_ppp_bm4d_admm.py
  examples/scripts/deconv_ppp_dncnn_admm.py
  examples/scripts/deconv_tv_admm.py
  examples/scripts/deconv_tv_admm_tune.py
  examples/scripts/denoise_tv_iso_multi.py
  examples/scripts/denoise_tv_iso_pgm.py
Labels: examples, developer

#296 Modify `FiniteDifference` linop
  scico/linop/__init__.py
  scico/linop/_diff.py
  scico/test/linop/test_diff.py
Labels: improvement

#299 Improve handling of `h_center` parameter in `linop.CircularConvolve`
  scico/linop/_circconv.py
  scico/test/linop/test_circconv.py
Labels: improvement

#305 Improve script and resolve context-dependent test failure
  misc/pytest/pytest_time.sh
  scico/test/test_random.py
Labels: tests, developer

#306 Update change summary
  CHANGES.rst
Labels: documentation, developer

#308 Add google colab badge
  README.rst
  docs/docs_requirements.txt
  docs/source/conf.py
Labels: documentation, examples

#307 Add separable Huber norm and minor docs improvements.
  docs/source/conf.py
  docs/source/style.rst
  scico/functional/_functional.py
  scico/functional/_indicator.py
  scico/functional/_norm.py
  scico/linop/_circconv.py
  scico/test/functional/test_core.py
Labels: documentation, improvement
