Repository lanl/scico, pull requests merged in 2022-09, with the labels that each got.

#329 Clean up `Operator` and `LinearOperator` module structure
  scico/_generic_operators.py
  scico/linop/__init__.py
  scico/linop/_circconv.py
  scico/linop/_convolve.py
  scico/linop/_diag.py
  scico/linop/_diff.py
  scico/linop/_func.py
  scico/linop/_linop.py
  scico/linop/_matrix.py
  scico/linop/_stack.py
  scico/linop/_util.py
  scico/linop/optics.py
  scico/linop/radon_astra.py
  scico/linop/radon_svmbir.py
  scico/numpy/_wrappers.py
  scico/operator/__init__.py
  scico/operator/_func.py
  scico/operator/_operator.py
  scico/operator/biconvolve.py
  scico/test/linop/test_func.py
  scico/test/linop/test_linop.py
Labels: improvement

#336 Address #335
  scico/operator/_operator.py
Labels: documentation, improvement

#339 Address #324
  scico/denoiser.py
  scico/functional/_denoiser.py
  scico/linop/radon_astra.py
  scico/linop/radon_svmbir.py
Labels: documentation

#253 Replaced gpu<->cpu copies with host_callback in minimize.
  scico/solver.py
  scico/test/test_solver.py
Labels: improvement

#343 Mitigate impact of #342
  .github/workflows/pytest.yml
  CHANGES.rst
  docs/source/exampledepend.rst
  examples/examples_requirements.txt
  requirements.txt
  scico/denoiser.py
Labels: bug, tests

#345 Fix conda script and work around #344
  misc/conda/make_conda_env.sh
  scico/test/linop/test_radon_svmbir.py
Labels: tests
