Repository lanl/scico, pull requests merged in 2022-10, with the labels that each got.

#355 Resolve issue #291
  scico/optimize/_admm.py
  scico/optimize/_common.py
  scico/optimize/_ladmm.py
  scico/optimize/_pgm.py
  scico/optimize/_primaldual.py
Labels: improvement

#354 Resolve issue #240
  scico/solver.py
  scico/test/test_solver.py
Labels: enhancement

#353 Indicator documentation notation
  scico/functional/_indicator.py
Labels: documentation

#358 Remove `jaxlib`/`jax` version tests in `scico/__init__.py`
  scico/__init__.py
  setup.py
Labels: bug

#362 Add references to JOSS paper
  README.rst
  docs/source/overview.rst
  docs/source/references.bib
Labels: documentation

#360 Resolve issue #356
  scico/linop/_matrix.py
  scico/test/linop/test_matrix.py
Labels: bug

#359 Fix support for building docs offline
  docs/source/conf.py
  requirements.txt
Labels: documentation
