Repository lanl/scico, pull requests merged in 2024-10, with the labels that each got.

#555 Changes required to support `jax` version 0.4.33
  .github/workflows/pytest_ubuntu.yml
  docs/source/install.rst
  examples/scripts/ct_astra_modl_train_foam2.py
  examples/scripts/ct_astra_odp_train_foam2.py
  examples/scripts/ct_astra_unet_train_foam2.py
  examples/scripts/deconv_modl_train_foam1.py
  examples/scripts/deconv_odp_train_foam1.py
  examples/scripts/denoise_dncnn_train_bsds.py
  requirements.txt
  scico/flax/examples/data_generation.py
  scico/flax/train/checkpoints.py
  scico/functional/_denoiser.py
  scico/numpy/_blockarray.py
  scico/numpy/_wrapped_function_lists.py
Labels: developer

#557 Fix `XRayTransform2D` projection dtype and docs
  scico/linop/xray/_xray.py
  scico/test/linop/xray/test_xray.py
Labels: documentation, tests

#561 Fix XRayTransform boundary conditions
  scico/linop/xray/_xray.py
  scico/test/linop/xray/test_xray_2d.py
  scico/test/linop/xray/test_xray_3d.py
Labels: bug

#558 Add filtered back projection for 2D projector
  CHANGES.rst
  docs/source/references.bib
  scico/linop/xray/_xray.py
  scico/test/linop/xray/test_xray_2d.py
Labels: enhancement

#565 Changes for release 0.0.6
  CHANGES.rst
  MANIFEST.in
  README.md
  examples/scripts/ct_astra_3d_tv_padmm.py
  requirements.txt
  scico/__init__.py
  scico/linop/xray/astra.py
Labels: developer

#567 Resolve #564
  scico/linop/xray/astra.py
Labels: improvement
