Repository lanl/scico, pull requests merged in 2024-07, with the labels that each got.

#538 Fix typo in docs
  scico/solver.py
Labels: documentation

#537 Fix 2D X-ray projector bugs
  examples/scripts/ct_multi_cs_tv_admm.py
  scico/linop/xray/_xray.py
  scico/test/linop/xray/test_xray.py
Labels: bug, examples

#545 Fix bug in tests and avoid variability in numerical precision across devices
  scico/__init__.py
  scico/test/linop/xray/test_astra.py
Labels: bug, tests, improvement

#543 Proposed changes to #541
  CHANGES.rst
  examples/scripts/ct_astra_datagen_foam2.py
  examples/scripts/ct_astra_modl_train_foam2.py
  examples/scripts/ct_astra_odp_train_foam2.py
  examples/scripts/ct_astra_unet_train_foam2.py
  examples/scripts/deconv_datagen_foam1.py
  examples/scripts/deconv_modl_train_foam1.py
  examples/scripts/deconv_odp_train_foam1.py
  examples/scripts/denoise_dncnn_train_bsds.py
  scico/flax/examples/__init__.py
  scico/flax/examples/data_generation.py
  scico/flax/examples/examples.py
  scico/linop/xray/_xray.py
  scico/test/flax/test_examples_flax.py
Labels: bug, tests

#541 Resolve #535
  CHANGES.rst
  examples/scripts/ct_astra_datagen_foam2.py
  examples/scripts/ct_astra_modl_train_foam2.py
  examples/scripts/ct_astra_odp_train_foam2.py
  examples/scripts/ct_astra_unet_train_foam2.py
  examples/scripts/deconv_datagen_foam1.py
  examples/scripts/deconv_modl_train_foam1.py
  examples/scripts/deconv_odp_train_foam1.py
  examples/scripts/denoise_dncnn_train_bsds.py
  requirements.txt
  scico/flax/examples/__init__.py
  scico/flax/examples/data_generation.py
  scico/flax/examples/examples.py
  scico/linop/xray/_xray.py
  scico/test/flax/test_examples_flax.py
Labels: bug, developer

#546 Bump maximum supported jax version to 0.4.31
  CHANGES.rst
  requirements.txt
Labels: packaging
